config/routes.rb
YEAR_REGEX = /\d\d\d\d/
KIND_REGEX = /G|I|income|expense/
AREA_REGEX = /functional|economic/

YEAR_CONTRAINTS = { year: YEAR_REGEX }
BUDGET_LINE_CONSTRAINTS = { year: YEAR_REGEX, kind: KIND_REGEX, area: AREA_REGEX }

Rails.application.routes.draw do
  root 'gobierto_budgets/pages#home'
  get "diputaciones" => "gobierto_budgets/pages#home", as: :deputation_root, defaults: { places_collection: "deputation_eu" }
  get "municipios" => "gobierto_budgets/pages#home", as: :place_root, defaults: { places_collection: "ine" }

  if Rails.env.development?
    get '/sandbox' => 'sandbox#index'
    get '/sandbox/*template' => 'sandbox#show'
  end

  # user and session management
  get 'login' => 'sessions#new', as: :login
  post 'sessions'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout
  resources :users, only: [:new, :create] do
    collection do
      post 'identify'
    end
    member do
      get 'verify'
    end
  end
  resource :user, only: [:edit, :update]
  resources :password_resets, only: [:new, :create, :update, :edit]

  get '/locale/:locale' => 'locale#update', as: :set_locale

  namespace :gobierto_budgets, path: '/', module: 'gobierto_budgets' do
    resources :featured_budget_lines, param: :organization_slug, only: [:show]
    get 'featured_budget_lines/embed/:organization_id', to: 'featured_budget_lines#embed', as: :featured_budget_lines

    namespace :api do
      get '/data/lines/:organization_slug/:year/:what' => 'data#lines', as: :data_lines
      get '/data/compare/:ine_codes/:year/:what' => 'data#compare', as: :data_compare
      get '/data/lines/budget_line/:organization_slug/:year/:what/:kind/:code/:area' => 'data#lines', as: :data_lines_budget_line
      get '/data/compare/budget_line/:ine_codes/:year/:what/:kind/:code/:area' => 'data#compare', as: :data_compare_budget_lines
      get '/data/widget/total_budget/:organization_slug/:year' => 'data#total_budget', as: :data_total_budget
      get '/data/widget/total_budget_per_inhabitant/:organization_slug/:year' => 'data#total_budget_per_inhabitant', as: :data_total_budget_per_inhabitant
      get '/data/widget/budget/:organization_slug/:year/:code/:area/:kind' => 'data#budget', as: :data_budget
      get '/data/widget/budget_execution/:organization_slug/:year/:code/:area/:kind' => 'data#budget_execution', as: :data_budget_execution
      get '/data/widget/budget_per_inhabitant/:organization_slug/:year/:code/:area/:kind' => 'data#budget_per_inhabitant', as: :data_budget_per_inhabitant
      get '/data/widget/budget_percentage_over_total/:organization_slug/:year/:code/:area/:kind' => 'data#budget_percentage_over_total', as: :data_budget_percentage_over_total
      get '/data/widget/budget_percentage_previous_year/:organization_slug/:year/:code/:area/:kind' => 'data#budget_percentage_previous_year', as: :data_budget_percentage_previous_year
      get '/data/widget/population/:ine_code/:year' => 'data#population', as: :data_population
      get '/data/widget/ranking/:places_collection/:year/:kind/:area/:variable(/:code)' => 'data#ranking', as: :data_ranking
      get '/data/widget/total_widget_execution/:organization_slug/:year' => 'data#total_budget_execution', as: :data_total_budget_execution
      get '/data/widget/budget_execution_deviation/:organization_slug/:year/:kind' => 'data#budget_execution_deviation', as: :data_budget_execution_deviation
      get '/data/widget/debt/:organization_slug/:year' => 'data#debt', as: :data_debt

      get '/data/widget/global_total_budget/:year' => 'global_data#total_budget', as: :global_data_total_budget
      get '/data/widget/global_total_budget_per_inhabitant/:year' => 'global_data#total_budget_per_inhabitant', as: :global_data_total_budget_per_inhabitant
      get '/data/widget/global_population/:year' => 'global_data#population', as: :global_data_population
      get '/data/widget/global_debt/:year' => 'global_data#debt', as: :global_data_debt
      get '/data/widget/global_total_budget_execution/:year' => 'global_data#total_budget_execution', as: :global_data_total_budget_execution

      get '/categories' => 'categories#index'
      get '/categories/:area/:kind' => 'categories#index'
      get '/places' => 'places#index'
      get '/data/:organization_slug/:year/:kind/:area' => 'data#budgets'
      get '/data/debt/:year' => 'data#municipalities_debt'
      get '/data/population/:year' => 'data#municipalities_population'

      get '/intelligence/budget_lines/:organization_slug/:years' => 'intelligence#budget_lines', as: :intelligence_budget_lines
      get '/intelligence/budget_lines_means/:organization_slug/:year' => 'intelligence#budget_lines_means', as: :intelligence_budget_lines_means
    end

    # statics
    get 'about' => 'pages#about'
    get 'pro' => 'pages#pro'
    get 'request_access' => 'pages#request_access'
    get 'contact_pro' => redirect('/users/new')
    get 'contact_citizen' => redirect('/users/new')
    get 'faq' => 'pages#faq'
    get 'legal/cookies' => 'pages#legal_cookies'
    get 'legal/legal' => 'pages#legal_legal'
    get 'legal/privacy' => 'pages#legal_privacy'

    get 'sobre-ca' => 'pages#about_ca'
    get 'sobre-es' => 'pages#about_es'

    get 'search' => 'search#index'
    get 'categories/:slug/:year/:area/:kind' => 'search#categories', as: :search_categories
    get '/mapas/:year' => 'pages#map', as: :map

    get '/budget_lines/*slug/:year/:code/:kind/:area/feedback/:question_id' => 'budget_lines#feedback', as: :budget_line_feedback, constraints: BUDGET_LINE_CONSTRAINTS

    # municipalities
    get "/municipios/*slug/partida/:year/:code/:kind/:area" => "budget_lines#show", as: :budget_line, constraints: BUDGET_LINE_CONSTRAINTS, defaults: { places_collection: "ine" }

    get '/municipios/*slug/:year/execution' => 'places#execution', as: :place_execution, constraints: YEAR_CONTRAINTS, defaults: { places_collection: "ine" }

    get '/municipios/*slug/inteligencia' => 'places#intelligence'
    get '/municipios/*slug/:year/debt' => 'places#debt_alive', constraints: YEAR_CONTRAINTS, defaults: { places_collection: "ine" }
    get '/municipios/:ine_code(/:year)/redirect' => 'places#redirect', constraints: YEAR_CONTRAINTS, defaults: { places_collection: "ine" }

    get "/municipios/*slug/:year" => "places#show", as: :place, constraints: YEAR_CONTRAINTS, defaults: { places_collection: "ine" }
    get "/municipios/*slug/:year/:kind/:area(/parent/:parent_code)" => "places#budget", as: :place_budget, constraints: BUDGET_LINE_CONSTRAINTS, defaults: { places_collection: "ine" }
    get "/municipios/*slug" => "places#show", defaults: { places_collection: "ine" }

    get 'compara/municipios' => 'pages#compare', as: :compare, defaults: { places_collection: "ine" }
    get 'compara/municipios/nueva' => 'pages#compare-new', defaults: { places_collection: "ine" }
    get '/compara/municipios/:slug_list/:year/:kind/:area' => 'places#compare', as: :places_compare, defaults: { places_collection: "ine" }

    get "/ranking/municipios/:year/:kind/:area/:variable(/:code)(/p/:page)" => "places#ranking", as: :places_ranking, defaults: { places_collection: "ine" }
    get "/ranking/municipios/:year/population(/:page)" => "places#ranking", as: :population_ranking, defaults: { places_collection: "ine" }

    get 'ranking/municipios' => 'pages#ranking', as: :ranking, defaults: { places_collection: "ine" }

    # deputations
    get "/diputaciones/*slug/partida/:year/:code/:kind/:area" => "budget_lines#show", as: :deputation_budget_line, constraints: BUDGET_LINE_CONSTRAINTS, defaults: { places_collection: "deputation_eu" }

    get "/diputaciones/*slug/:year/execution" => "places#execution", as: :deputation_execution, constraints: YEAR_CONTRAINTS, defaults: { places_collection: "deputation_eu" }

    get "/diputaciones/*slug/:year" => "places#show", as: :deputation, constraints: YEAR_CONTRAINTS, defaults: { places_collection: "deputation_eu" }
    get "/diputaciones/*slug/:year/:kind/:area(/parent/:parent_code)" => "places#budget", as: :deputation_budget, constraints: BUDGET_LINE_CONSTRAINTS, defaults: { places_collection: "deputation_eu" }
    get "/diputaciones/*slug" => "places#show", defaults: { places_collection: "deputation_eu" }

    # deputations compare
    get 'compara/diputaciones' => 'pages#compare', as: :deputations_compare, defaults: { places_collection: "deputation_eu" }
    get 'compara/diputaciones/nueva' => 'pages#compare-new', defaults: { places_collection: "deputation_eu" }
    get '/compara/diputaciones/:slug_list/:year/:kind/:area' => 'places#compare', as: :deputations_places_compare, defaults: { places_collection: "deputation_eu" }

    get "/ranking/diputaciones/:year/:kind/:area/:variable(/:code)(/p/:page)" => "places#ranking", as: :deputations_places_ranking, defaults: { places_collection: "deputation_eu" }
    get "/ranking/diputaciones/:year/population(/:page)" => "places#ranking", as: :deputations_population_ranking, defaults: { places_collection: "deputation_eu" }

    get 'ranking/diputaciones' => 'pages#deputations_ranking', as: :deputations_ranking, defaults: { places_collection: "deputation_eu" }

    # feedback
    resources :answers, only: [:create]

    # follow place
    resources :subscriptions, only: [:create, :destroy]
  end
end

app/models/concerns/gobierto_budgets/common_query_behavior.rb
module GobiertoBudgets
  module CommonQueryBehavior
    extend ActiveSupport::Concern

    included do

      def self.append_to_terms(terms, items, key = :ine_code)
        return if items.compact.blank?

        terms << { terms: { key => items.compact } }
      end

      def append_to_terms(terms, items, key = :ine_code)
        self.class.append_to_terms(terms, items, key)
      end

      def self.append_ine_codes(terms, ine_codes) = append_to_terms(terms, ine_codes)

      def append_ine_codes(terms, ine_codes) = append_to_terms(terms, ine_codes)

      def self.append_organization_ids(terms, organization_ids) = append_to_terms(terms, organization_ids, :organization_id)

      def append_organization_ids(terms, organization_ids) = append_to_terms(terms, organization_ids, :organization_id)
    end
  end
end

app/models/concerns/gobierto_budgets/describable.rb
module GobiertoBudgets
  module Describable
    extend ActiveSupport::Concern

    module ClassMethods
      def all_descriptions
        @all_descriptions ||= begin
                                h = {}
                                default_path = "./db/data/budget_line_descriptions_#{I18n.default_locale}.yml"
                                raise "Missing default locale file #{default_path}" unless File.file?(default_path)

                                I18n.available_locales.each do |locale|
                                  path = "./db/data/budget_line_descriptions_#{locale}.yml"
                                  unless File.file?(path)
                                    path = default_path
                                  end
                                  h[locale] = YAML.load_file(path)
                                end
                                h
                              end
      end
    end
  end
end

app/models/gobierto_budgets.rb
module GobiertoBudgets; end

app/models/gobierto_budgets/answer.rb
module GobiertoBudgets
  class Answer < ActiveRecord::Base
    QUESTION_1_ANSWERS = ['Sí', 'No']
    QUESTION_2_ANSWERS = ['Poco', 'Apropiado', 'Mucho']

    def self.percentages_for_question(question_id, options)
      scoped = where({question_id: question_id}.merge(options))

      total = scoped.count
      groups = scoped.select('id, answer_text').group_by do |a|
        a.answer_text
      end

      Hash[groups.map do |answer_text, list|
        [answer_text, ((list.length.to_f * 100.0) / total).round(1)]
      end]
    end
  end
end

app/models/gobierto_budgets/associated_entity.rb
module GobiertoBudgets
  class AssociatedEntity < ActiveRecord::Base

    self.table_name = "gobierto_budgets_associated_entities"

    validates :name, presence: true, uniqueness: { scope: :ine_code }
    validates :slug, presence: true, uniqueness: true # Can't scope on ine_code, URLs just pass one parameter
    validates :entity_id, presence: true, uniqueness: { scope: :ine_code }
    validates :ine_code, presence: true

    scope :by_place, ->(place) { where(ine_code: place.id) }

    before_validation :set_slug

    def total_expenses(year)
      BudgetTotal.budgeted_for(entity_id, year, BudgetLine::EXPENSE)
    rescue Elasticsearch::Transport::Transport::Errors::NotFound
      nil
    end

    def total_income(year)
      BudgetTotal.budgeted_for(entity_id, year, BudgetLine::INCOME)
    rescue Elasticsearch::Transport::Transport::Errors::NotFound
      nil
    end

    def combined_slug
      "#{associated_municipality.slug}/#{slug}"
    end

    private

    def associated_municipality
      INE::Places::Place.find(ine_code)
    end

    def set_slug
      return if slug.present?

      base_slug = name.parameterize
      new_slug = base_slug

      count = 2

      while self.class.exists?(slug: new_slug)
        new_slug = "#{base_slug}-#{count}"
        count += 1
      end

      self.slug = new_slug
    end

  end
end

app/models/gobierto_budgets/budget_line_stats.rb
module GobiertoBudgets
  class BudgetLineStats
    def initialize(options)
      @site = options.fetch :site
      @place = @site.place
      @budget_line = options.fetch :budget_line
      @kind = @budget_line.kind
      @area_name = @budget_line.area_name
      @year = @budget_line.year.to_i
      @code = @budget_line.code
    end

    def amount(year = nil)
      budget_line_planned_query(year, 'amount')
    end
    alias_method :amount_planned, :amount

    def amount_executed(year = nil)
      budget_line_executed_query(year, 'amount')
    end

    def amount_per_inhabitant(year = nil)
      budget_line_planned_query(year, 'amount_per_inhabitant')
    end

    def percentage_of_total(year = nil)
      diff = (amount(year) / total_budget).to_f * 100

      "#{ActionController::Base.helpers.number_with_precision(diff, precision: 2)}%"
    end

    def percentage_difference(options)
      year = options.fetch(:year, @year)
      variable1 = options.fetch(:variable1)
      variable2 = options.fetch(:variable2, options.fetch(:variable1))

      diff = if variable1 == variable2
               year1 = options.fetch(:year1)
               year2 = options.fetch(:year2)

               v1 = self.send(variable1, year1)
               v2 = self.send(variable1, year2)
               return nil if v1.nil? || v2.nil?

               ((v1.to_f - v2.to_f)/v2.to_f) * 100
             else
               v1 = self.send(variable1, year)
               v2 = self.send(variable2, year)
               return nil if v1.nil? || v2.nil?

               ((v1.to_f - v2.to_f)/v2.to_f) * 100
             end

      if(diff < 0)
        direction = 'menos'
        diff = diff*-1
      else
        direction = 'más'
      end

      if diff == Float::INFINITY
        return nil
      else
        "#{ActionController::Base.helpers.number_with_precision(diff, precision: 2)}% #{direction}"
      end
    end

    def mean_province
      mean_province_query(@year, 'amount')
    end

    private

    def total_budget
      total_budget_planned_query(@year, 'total_budget')
    end

    def budget_line_planned_query(year, attribute)
      year ||= @year
      result = GobiertoBudgets::SearchEngine.client.get index: GobiertoBudgets::SearchEngineConfiguration::BudgetLine.index_forecast, id: [@place.id, year, @code, @kind, @area_name].join('/')
      result['_source'][attribute]
    rescue Elasticsearch::Transport::Transport::Errors::NotFound
      nil
    end

    def budget_line_executed_query(year, attribute)
      year ||= @year
      result = GobiertoBudgets::SearchEngine.client.get index: GobiertoBudgets::SearchEngineConfiguration::BudgetLine.index_executed, id: [@place.id, year, @code, @kind, @area_name].join('/')
      result['_source'][attribute]
    rescue Elasticsearch::Transport::Transport::Errors::NotFound
      nil
    end

    def total_budget_planned_query(year, attribute)
      result = GobiertoBudgets::SearchEngine.client.get index: GobiertoBudgets::SearchEngineConfiguration::TotalBudget.index_forecast, id: [@place.id, year, @kind, GobiertoBudgets::SearchEngineConfiguration::TotalBudget.type].join('/')
      result['_source'][attribute].to_f
    rescue Elasticsearch::Transport::Transport::Errors::NotFound
      nil
    end

    def mean_province_query(year, attribute)
      filters = [ {term: { province_id: @place.province_id }} ]
      filters.push({term: { code: @code }})
      filters.push({term: { kind: @kind }})
      filters.push({term: { year: year }})
      filters.push({term: { type: @area_name }})

      query = {
        query: {
          bool: {
            must: filters
          }
        },
        size: 10_000,
        "aggs": {
          "#{attribute}_per_year": {
            "terms": {
              "field": "year",
              size: 10_000
            },
            "aggs": {
              "budget_sum": {
                "sum": {
                  "field": "#{attribute}"
                }
              }
            }
          }
        }
      }

      response = GobiertoBudgets::SearchEngine.client.search index: GobiertoBudgets::SearchEngineConfiguration::BudgetLine.index_forecast, body: query

      result = nil
      response['aggregations']["#{attribute}_per_year"]['buckets'].each do |r|
        result = (r['budget_sum']['value'].to_f / r['doc_count'].to_f).round(2)
      end
      result
    end
  end
end

app/models/gobierto_budgets/economic_area.rb
module GobiertoBudgets
  class EconomicArea
    include GobiertoBudgetsData::GobiertoBudgets::Describable
    include GobiertoBudgetsData::GobiertoBudgets::Searchable

    def self.area_name
      "economic"
    end
  end
end

app/views/custom/gobierto_budgets/pages/_compare_big.html.erb
<% place_type = GobiertoBudgetsData::GobiertoBudgets::PlaceDecorator.place_type(places_collection_key) %>
<h2 class="section_heading"><%= t(".#{places_collection_key}.compare") %></h2>

<%= form_tag '#', id: 'compare_form' do %>

  <%= image_tag('illustrations/integra.jpg') %>

  <p class="center"><%= t(".#{places_collection_key}.select") %></p>

  <input type="text" class="search_compare" value="" placeholder="<%= t(".#{places_collection_key}.search", n: 1) %>" name="place1" />
  <input type="text" class="search_compare" value="" placeholder="<%= t(".#{places_collection_key}.search", n: 2) %>" name="place2" />
  <input type="text" class="search_compare" value="" placeholder="<%= t(".#{places_collection_key}.search", n: 3) %>" name="place3" />

  <%= submit_tag t('.compare'), disabled: "true" %>

<% end %>

<div class="examples center">

  <p><%= t('.check_some_examples') %></p>

  <ul>
    <li><%= link_to 'Barcelona + Lleida + Girona + Tarragona', "/compare/barcelona:lleida:girona:tarragona/#{GobiertoBudgets::SearchEngineConfiguration::Year.last}/G/economic", class: 'button' %></li>
    <li><%= link_to 'Vic + Mataró + Badalona + Reus', "/compare/vic:mataro:badalona:reus/#{GobiertoBudgets::SearchEngineConfiguration::Year.last}/G/economic", class: 'button' %></li>
  </ul>

  <p><%= link_to t('.how_it_works'), '', class: 'toggle_div', data: { target: 'how_it_works' } %></strong></p>

  <div class="how_it_works" style="display: none;">

    <p><%= t(".#{places_collection_key}.description") %></p>

    <%= image_tag 'gobierto_compare_demo.gif', width: '100%' %>

  </div>
</div>

<% content_for(:javascript) do %>

function extractFormParameters($sel){
  var slugs = [];
  $sel.serializeArray().forEach(function(e){
    if(/^place/.test(e.name) && e.value !== ""){
      slugs.push(e.value);
    }
  });
  return slugs;
}

var searchOptions = {
  lookup: function (query, done) {
    $.ajax('<%= Settings.places_file || "/places.json" %>', {
      complete: function(data) {
        var suggestions = data.responseJSON.filter(function(result){
        return result.data.type == '<%= place_type %>' && (
          result.value.indexOf(query) !== -1 ||
          result.data.slug.indexOf(query) !== -1 ||
          result.value.toLowerCase().indexOf(query) !== -1
        )
        });
        var result = {
          suggestions: suggestions
        };
        done(result);
      }
    })
  },
  onSelect: function(suggestion) {
    if(suggestion.data.type == '<%= place_type %>') {
      ga('send', 'event', 'Compare Search', 'Click', 'Search', {nonInteraction: true});
      if(mixpanel.length > 0) {
        mixpanel.track('Compare Search', { '<%= place_type %>': suggestion.data.slug});
      }
      $(this).val(suggestion.data.slug);
      $(this).nextAll('input[type!=hidden]').first().focus();

      if(extractFormParameters($('form')).length > 1) {
        $('form input:submit').attr('disabled', false);
      }
    }
  },
  groupBy: 'category'
};

$('.search_compare').autocomplete($.extend({}, AUTOCOMPLETE_DEFAULTS(), searchOptions));

$('#compare_form').on('submit', function(e){
  e.preventDefault();
  var slugs = extractFormParameters($(this));
  if(slugs.length > 0) {
    Turbolinks.visit('<%= locations_compare_path %>/' + slugs.join(':') + '/<%= Date.today.year - 1 %>/G/functional');
  }
});

<% end %>

app/views/custom/gobierto_budgets/pages/home.html.erb
<%= flush_the_flash %>

<div class="pre_home">

  <h2><%= t('.subtitle') %></h2>

  <input type="text" class="places_search search_auto" placeholder="<%= t(".#{places_collection_key}.search_location") %>" autofocus="true">

  <p class="example"><%= t('.for_example') %>:
    <%= link_to 'Barcelona', '/places/barcelona' %>, <%= link_to 'Lleida', '/places/lleida'  %>, <%= link_to 'Girona', '/places/girona'  %>, <%= link_to 'Tarragona', '/places/tarragona'  %>.
  </p>

  <div class="home_section">
    <%= render partial: 'gobierto_budgets/pages/compare_big' %>
  </div>

  <div class="home_section">
    <h2 class="section_heading"><%= t('.explore_rankings') %></h2>

    <%= form_tag gobierto_budgets_places_ranking_path(GobiertoBudgets::SearchEngineConfiguration::Year.last,'G','functional','amount'), method: 'GET' do %>
      <%= hidden_field_tag 'f[aarr]' %>
      <div id="explore_prompt">
        <%= t('.explore_the_ranking_for') %>
        <div id="home_kind_switcher" class="switcher kind_switcher">
          <%= link_to "#{t('common.expenses')} <i class='fa fa-angle-down'></i>".html_safe, '#', data: {value: 'G'}, class: 'selected' %>
          <ul>
            <li><%= link_to t('common.expenses'), '#', data: {value: 'G'} %></li>
            <li><%= link_to t('common.incomes'), '#', data: {value: 'I'} %></li>
          </ul>
        </div>
        <%= t('.for_municipalities_of') %> Catalunya
        <%= submit_tag t('.explore') %>
      </div>
    <% end %>

    <p id="ranking_examples"><%= t('.some_examples') %></p>

        <div class="ranking_cards_carousel">
      <div class="nav left_side"><a href='#' class='prev'>&lt;</a></div>
      <div class="the_content">
        <% ranking_examples_args = {
             ine: [
               ["I", "economic", "amount", 344],
               ["G", "functional", "amount_per_inhabitant", 336],
               ["G", "functional", "amount", 342],
               ["G", "functional", "amount_per_inhabitant", 165],
               ["G", "functional", "amount", 162],
               ["G", "functional", "amount_per_inhabitant", 44],
               ["I", "economic", "amount", 313],
               ["G", "functional", "amount_per_inhabitant", 171]
             ],
             deputation_eu: [
             ]
        } %>

      <% ranking_examples_args[places_collection_key].each_with_index do |args, i|
           widget_api_path = gobierto_budgets_api_data_ranking_path(
             GobiertoBudgets::SearchEngineConfiguration::Year.last,
             *args,
             format: :json,
             only_municipalities: true,
             places_collection: places_collection_key
           ) %>
            <div class="ranking_card clearfix"
                data-widget-type="ranking_<%= i %>"
                data-widget-template="#widget-template"
                data-widget-data-url="<%= widget_api_path %>">
            </div>
      <% end %>

      </div>
      <div class="nav right_side"><a href='#' class='next'>&gt;</a></div>

    </div>
  </div>

</div>

<%= render partial: 'gobierto_budgets/pages/ranking_card_template' %>

<% content_for :javascript do %>

  $('[data-widget-type]:first').siblings().hide();
  $('a.next').click(function(e) {
    e.preventDefault();
    var current_widget = $('[data-widget-type]:visible');
    var next_widget = (current_widget.next().length > 0) ? current_widget.next() : current_widget.siblings().first();

    current_widget.velocity('transition.slideLeftLongOut');
    next_widget.velocity('transition.slideRightLongIn');
  })

  $('a.prev').click(function(e) {
    e.preventDefault();
    var current_widget = $('[data-widget-type]:visible');
    var prev_widget = (current_widget.prev().length > 0) ? current_widget.prev() : current_widget.siblings().last();

    current_widget.velocity('transition.slideRightLongOut');
    prev_widget.velocity('transition.slideLeftLongIn');
  })

<% end %>

<%= render partial: "custom/layouts/opendata_#{I18n.locale}" %>