config/routes.rb
YEAR_REGEX = /\d\d\d\d/
KIND_REGEX = /G|I|income|expense/
AREA_REGEX = /functional|economic/

YEAR_CONTRAINTS = { year: YEAR_REGEX }
BUDGET_LINE_CONSTRAINTS = { year: YEAR_REGEX, kind: KIND_REGEX, area: AREA_REGEX }

Rails.application.routes.draw do
  root 'gobierto_budgets/pages#home'
  get "diputaciones" => "gobierto_budgets/pages#home", as: :deputation_root, defaults: { places_collection: "deputation_eu" }
  get "municipios" => "gobierto_budgets/pages#home", as: :place_root, defaults: { places_collection: "ine" }

  if Rails.env.development?
    get '/sandbox' => 'sandbox#index'
    get '/sandbox/*template' => 'sandbox#show'
  end

  # user and session management
  get 'login' => 'sessions#new', as: :login
  post 'sessions'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout
  resources :users, only: [:new, :create] do
    collection do
      post 'identify'
    end
    member do
      get 'verify'
    end
  end
  resource :user, only: [:edit, :update]
  resources :password_resets, only: [:new, :create, :update, :edit]

  get '/locale/:locale' => 'locale#update', as: :set_locale

  namespace :gobierto_budgets, path: '/', module: 'gobierto_budgets' do
    resources :featured_budget_lines, param: :organization_slug, only: [:show]
    get 'featured_budget_lines/embed/:organization_id', to: 'featured_budget_lines#embed', as: :featured_budget_lines

    namespace :api do
      get '/data/lines/:organization_slug/:year/:what' => 'data#lines', as: :data_lines
      get '/data/compare/:ine_codes/:year/:what' => 'data#compare', as: :data_compare
      get '/data/lines/budget_line/:organization_slug/:year/:what/:kind/:code/:area' => 'data#lines', as: :data_lines_budget_line
      get '/data/compare/budget_line/:ine_codes/:year/:what/:kind/:code/:area' => 'data#compare', as: :data_compare_budget_lines
      get '/data/widget/total_budget/:organization_slug/:year' => 'data#total_budget', as: :data_total_budget
      get '/data/widget/total_budget_per_inhabitant/:organization_slug/:year' => 'data#total_budget_per_inhabitant', as: :data_total_budget_per_inhabitant
      get '/data/widget/budget/:organization_slug/:year/:code/:area/:kind' => 'data#budget', as: :data_budget
      get '/data/widget/budget_execution/:organization_slug/:year/:code/:area/:kind' => 'data#budget_execution', as: :data_budget_execution
      get '/data/widget/budget_per_inhabitant/:organization_slug/:year/:code/:area/:kind' => 'data#budget_per_inhabitant', as: :data_budget_per_inhabitant
      get '/data/widget/budget_percentage_over_total/:organization_slug/:year/:code/:area/:kind' => 'data#budget_percentage_over_total', as: :data_budget_percentage_over_total
      get '/data/widget/budget_percentage_previous_year/:organization_slug/:year/:code/:area/:kind' => 'data#budget_percentage_previous_year', as: :data_budget_percentage_previous_year
      get '/data/widget/population/:ine_code/:year' => 'data#population', as: :data_population
      get '/data/widget/ranking/:places_collection/:year/:kind/:area/:variable(/:code)' => 'data#ranking', as: :data_ranking
      get '/data/widget/total_widget_execution/:organization_slug/:year' => 'data#total_budget_execution', as: :data_total_budget_execution
      get '/data/widget/budget_execution_deviation/:organization_slug/:year/:kind' => 'data#budget_execution_deviation', as: :data_budget_execution_deviation
      get '/data/widget/debt/:organization_slug/:year' => 'data#debt', as: :data_debt

      get '/data/widget/global_total_budget/:year' => 'global_data#total_budget', as: :global_data_total_budget
      get '/data/widget/global_total_budget_per_inhabitant/:year' => 'global_data#total_budget_per_inhabitant', as: :global_data_total_budget_per_inhabitant
      get '/data/widget/global_population/:year' => 'global_data#population', as: :global_data_population
      get '/data/widget/global_debt/:year' => 'global_data#debt', as: :global_data_debt
      get '/data/widget/global_total_budget_execution/:year' => 'global_data#total_budget_execution', as: :global_data_total_budget_execution

      get '/categories' => 'categories#index'
      get '/categories/:area/:kind' => 'categories#index'
      get '/places' => 'places#index'
      get '/data/:organization_slug/:year/:kind/:area' => 'data#budgets'
      get '/data/debt/:year' => 'data#municipalities_debt'
      get '/data/population/:year' => 'data#municipalities_population'

      get '/intelligence/budget_lines/:organization_slug/:years' => 'intelligence#budget_lines', as: :intelligence_budget_lines
      get '/intelligence/budget_lines_means/:organization_slug/:year' => 'intelligence#budget_lines_means', as: :intelligence_budget_lines_means
    end

    # statics
    get 'about' => 'pages#about'
    get 'pro' => 'pages#pro'
    get 'request_access' => 'pages#request_access'
    get 'contact_pro' => redirect('/users/new')
    get 'contact_citizen' => redirect('/users/new')
    get 'faq' => 'pages#faq'
    get 'legal/cookies' => 'pages#legal_cookies'
    get 'legal/legal' => 'pages#legal_legal'
    get 'legal/privacy' => 'pages#legal_privacy'

    get 'sobre-ca' => 'pages#about_ca'
    get 'sobre-es' => 'pages#about_es'

    get 'search' => 'search#index'
    get 'categories/:slug/:year/:area/:kind' => 'search#categories', as: :search_categories
    get '/mapas/:year' => 'pages#map', as: :map

    get '/budget_lines/*slug/:year/:code/:kind/:area/feedback/:question_id' => 'budget_lines#feedback', as: :budget_line_feedback, constraints: BUDGET_LINE_CONSTRAINTS

    # municipalities
    get "/municipios/*slug/partida/:year/:code/:kind/:area" => "budget_lines#show", as: :budget_line, constraints: BUDGET_LINE_CONSTRAINTS, defaults: { places_collection: "ine" }

    get '/municipios/*slug/:year/execution' => 'places#execution', as: :place_execution, constraints: YEAR_CONTRAINTS, defaults: { places_collection: "ine" }

    get '/municipios/*slug/inteligencia' => 'places#intelligence'
    get '/municipios/*slug/:year/debt' => 'places#debt_alive', constraints: YEAR_CONTRAINTS, defaults: { places_collection: "ine" }
    get '/municipios/:ine_code(/:year)/redirect' => 'places#redirect', constraints: YEAR_CONTRAINTS, defaults: { places_collection: "ine" }

    get "/municipios/*slug/:year" => "places#show", as: :place, constraints: YEAR_CONTRAINTS, defaults: { places_collection: "ine" }
    get "/municipios/*slug/:year/:kind/:area(/parent/:parent_code)" => "places#budget", as: :place_budget, constraints: BUDGET_LINE_CONSTRAINTS, defaults: { places_collection: "ine" }
    get "/municipios/*slug" => "places#show", defaults: { places_collection: "ine" }

    get 'compara/municipios' => 'pages#compare', as: :compare, defaults: { places_collection: "ine" }
    get 'compara/municipios/nueva' => 'pages#compare-new', defaults: { places_collection: "ine" }
    get '/compara/municipios/:slug_list/:year/:kind/:area' => 'places#compare', as: :places_compare, defaults: { places_collection: "ine" }

    get "/ranking/municipios/:year/:kind/:area/:variable(/:code)(/p/:page)" => "places#ranking", as: :places_ranking, defaults: { places_collection: "ine" }
    get "/ranking/municipios/:year/population(/:page)" => "places#ranking", as: :population_ranking, defaults: { places_collection: "ine" }

    get 'ranking/municipios' => 'pages#ranking', as: :ranking, defaults: { places_collection: "ine" }

    # deputations
    get "/diputaciones/*slug/partida/:year/:code/:kind/:area" => "budget_lines#show", as: :deputation_budget_line, constraints: BUDGET_LINE_CONSTRAINTS, defaults: { places_collection: "deputation_eu" }

    get "/diputaciones/*slug/:year/execution" => "places#execution", as: :deputation_execution, constraints: YEAR_CONTRAINTS, defaults: { places_collection: "deputation_eu" }

    get "/diputaciones/*slug/:year" => "places#show", as: :deputation, constraints: YEAR_CONTRAINTS, defaults: { places_collection: "deputation_eu" }
    get "/diputaciones/*slug/:year/:kind/:area(/parent/:parent_code)" => "places#budget", as: :deputation_budget, constraints: BUDGET_LINE_CONSTRAINTS, defaults: { places_collection: "deputation_eu" }
    get "/diputaciones/*slug" => "places#show", defaults: { places_collection: "deputation_eu" }

    # deputations compare
    get 'compara/diputaciones' => 'pages#compare', as: :deputations_compare, defaults: { places_collection: "deputation_eu" }
    get 'compara/diputaciones/nueva' => 'pages#compare-new', defaults: { places_collection: "deputation_eu" }
    get '/compara/diputaciones/:slug_list/:year/:kind/:area' => 'places#compare', as: :deputations_places_compare, defaults: { places_collection: "deputation_eu" }

    get "/ranking/diputaciones/:year/:kind/:area/:variable(/:code)(/p/:page)" => "places#ranking", as: :deputations_places_ranking, defaults: { places_collection: "deputation_eu" }
    get "/ranking/diputaciones/:year/population(/:page)" => "places#ranking", as: :deputations_population_ranking, defaults: { places_collection: "deputation_eu" }

    get 'ranking/diputaciones' => 'pages#deputations_ranking', as: :deputations_ranking, defaults: { places_collection: "deputation_eu" }

    # feedback
    resources :answers, only: [:create]

    # follow place
    resources :subscriptions, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include UserSession

  has_secure_password validations: false

  attr_accessor :remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :first_name, length: { maximum: 50 }
  validates :last_name, length: { maximum: 50 }
  validates :password, length: { minimum: 5 }, presence: true, confirmation: true, on: :update, if: Proc.new{|u| u.pending_confirmation? }
  validates :terms_of_service, acceptance: { accept: true }, on: :update
  validates :place_id, presence: true, on: :update

  before_validation :sanitize_parameters
  before_create :set_verification_token
  after_create :send_verification_email
  after_save :to_mailchimp

  scope :sorted, -> { order(id: :desc) }
  scope :admin, -> { where(admin: true) }
  scope :regular, -> { where(admin: false) }

  has_many :subscriptions, dependent: :destroy, class_name: "GobiertoBudgets::Subscription"

  def full_name
    @full_name ||= [first_name, last_name].compact.join(' ')
  end

  def pending_confirmation?
    self.verification_token.present?
  end

  def clear_verification_token
    self.verification_token = nil
  end

  def update_pending_answers(session_id)
    GobiertoBudgets::Answer.where(temporary_user_id: session_id.to_s).update_all(user_id: self.id, temporary_user_id: nil)
  end

  def has_replied?(options)
    GobiertoBudgets::Answer.where(options.merge(user_id: self.id)).first
  end

  def answered_consultation?(consultation)
    answers.where(consultation_id: consultation.id).exists?
  end

  def get_subscriptions_on(place)
    if place
      subscriptions.find_by(place_id: place.id)
    end
  end

  def location_by_collection(collection_key)
    return if place_id.blank?

    GobiertoBudgetsData::GobiertoBudgets::PlaceDecorator.collection(collection_key).find do |location|
      location.population_place_ids.include? place_id.to_s
    end
  end

  def in_mailchimp?
    Mailchimp.is_member?(self)
  end

  private

  def set_verification_token
    self.verification_token = generate_token
  end

  def sanitize_parameters
    self.email = self.email.downcase.strip if self.email.present?
    self.first_name = self.first_name.strip if self.first_name.present?
    self.last_name = self.last_name.strip if self.last_name.present?
  end

  def send_verification_email
    UserMailer.verification_notification(self).deliver_now
  end

  def to_mailchimp
    ::UpdateOrCreateInMailchimpJob.perform_later(self) if Rails.env.production?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'gobierto_budgets_application'

  before_action :check_users_enabled
  before_action :load_current_user, only: [:edit, :update]

  def new
    redirect_to edit_user_path if logged_in?

    @user = User.new(params.permit(:place_id, :pro))
    @place_id = params[:place_id]
  end

  def create
    @user = User.new create_user_params
    if @user.save
      redirect_to location_root_path, notice: 'Por favor, confirma tu email'
    else
      render 'new'
    end
  end

  def identify
    @user = User.find_or_initialize_by email: params[:user][:email]
    if @user.new_record?
      @user.attributes = create_user_params
      if @user.save
        created = true
      else
        render 'new' and return
      end
    end
    session[:follow] = params[:follow] if params[:follow]

    respond_to do |format|
      format.html do
        if created
          redirect_to location_root_path, notice: 'Por favor, confirma tu email'
        else
          redirect_back fallback_location: location_root_path
        end
      end
      format.js do
        @form_context = params[:context]
        (created || @user.pending_confirmation?) ? render('created') : render('login')
      end
    end
  end

  def verify
    @user = User.find_by! verification_token: params[:id]
    log_in(@user)
  end

  def edit
  end

  def update
    if @user.update(update_user_params)
      if @user.pending_confirmation?
        @user.clear_verification_token
        @user.update_pending_answers(session.id)
        store_subscriptions
      end
      @user.save!
      redirect_to location_root_path, notice: 'Datos actualizados correctamente'
    else
      flash.now.alert = 'No se han podido actualizar los datos'
      render 'edit'
    end
  end

  private

  def create_user_params
    params.require(:user).permit(:first_name, :last_name, :email, :place_id, :pro, :terms_of_service)
  end

  def update_user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :place_id, :pro, :terms_of_service)
  end

  def load_current_user
    redirect_to login_path and return unless logged_in?

    @user = current_user
  end
end

app/views/users/_alerts.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <p>El formulario tiene <%= pluralize(@user.errors.count, "error") %>:</p>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_basic_fields.html.erb
<div class="form_item">
  <div class="form_item_cont">
    <%= f.label :email, "E-mail" %>
    <%= f.email_field :email, class: 'i_text' %>
  </div>
</div>

<div class="form_item">
  <div class="form_item_cont">
    <%= f.label :place_id, "Tu municipio" %>
    <% if f.object.place_id.blank? || f.object.new_record?  %>
      <%= f.select :place_id, places_for_select, {include_blank: true, selected: "#{@place_id || f.object.place_id}"}, {class: 'select2'} %>
      <div class="submit_item explanation"><small>(El municipio donde resides. Además de a éste, podrás seguir a otros para recibir sus actualizaciones)</small></div>
    <% else %>
      <input type="text" value="<%= INE::Places::Place.find(f.object.place_id).name %>" class="i_text" disabled="true"/>
      <span style="color:red">*</span> <small><em>si quieres volver a cambiar tu municipio <%= link_to 'contacta con nosotros', gobierto_budgets_about_path(anchor: 'contact') %></em></small>
    <% end %>
  </div>
</div>

<div class="form_item">
  <div class="form_item_cont">
    <label>Eres:</label>

    <div class="radio_option">
      <%= f.radio_button :pro, false, :"data-user-type" => 'Citizen' %> <%= f.label :pro_false, "Ciudadano" %>
    </div>
    <div class="radio_option">
      <%= f.radio_button :pro, true, :"data-user-type" => 'Professional' %> <%= f.label :pro_true, "Profesional de la administración local" %>
    </div>
  </div>
</div>

<% if params[:pro] == 'true' %>
  <div class="form_item">
    <div class="form_item_cont">
      <label>Teléfono</label>
      <%= telephone_field :lead, :phone, class: 'i_text' %>
    </div>
  </div>
<% end %>

<% content_for(:javascript) do %>
  $('.select2').select2({
    width: '300px',
    ajax: {
      url: "/api/places",
      dataType: 'json',
      delay: 250,
      data: function(params) {
        return {
          q: params.term
        };
      },
      processResults: function(data) {
        return {
          results: $.map(data, function (item) {
            return {
              text: item.value,
              id: item.data.id
            }
          })
        };
      },
      cache: true
    },
    escapeMarkup: function (markup) { return markup; },
    minimumInputLength: 3
  });

<% end %>

app/views/users/_form.html.erb
<div class="form clearfix">
  <%= render 'alerts' %>

  <%= form_for @user do |f| %>
    <div class="form_item">
      <div class="form_item_cont">
        <%= f.label :first_name, "Nombre" %>
        <%= f.text_field :first_name, class: 'i_text', autofocus: true, placeholder: '(opcional)'  %>
      </div>
    </div>

    <div class="form_item">
      <div class="form_item_cont">
        <%= f.label :last_name, "Apellidos" %>
        <%= f.text_field :last_name, class: 'i_text', placeholder: '(opcional)' %>
      </div>
    </div>

    <%= render partial: 'basic_fields', locals: {f:f} %>

    <div class="form_item">
      <div class="form_item_cont">
        <%= f.label :password, "Contraseña" %>
        <%= f.password_field :password, class: 'i_text', autofocus: true %>
      </div>
    </div>

    <div class="form_item">
      <div class="form_item_cont">
        <%= f.label :password_confirmation, "Confirma la contraseña" %>
        <%= f.password_field :password_confirmation, class: 'i_text' %>
      </div>
    </div>

    <div class="form_item full submit_item">
      <div class="form_item_cont clearfix">
        <div class="conditions">
          <% unless f.object.terms_of_service? %>
            <p>También recibirás novedades sobre Gobierto Presupuestos Municipales de vez en cuando. Podrás dejar de recibir cuando quieras.</p>
            <label><%= f.check_box :terms_of_service %> He leído el <%= link_to 'Aviso legal', gobierto_budgets_legal_legal_path, target: 'blank' %> y la <%= link_to 'Política de privacidad', gobierto_budgets_legal_privacy_path, target: 'blank' %></label>
          <% end %>
        </div>
        <%= hidden_field_tag :back_url, request.referer %>
        <input type="submit" class="submit" value="Enviar">
      </div>
    </div>
  <% end %>
</div>

app/views/users/created.js.erb
$('#new_user').hide();
$('.share_post_submit').toggleClass('hidden').show();

app/views/users/edit.html.erb
<div class="cont clearfix">
  
  <%= flush_the_flash %>

  <h1>Edita tus datos personales</h1>
  <p class="highlight">Tus datos personales y opiniones serán siempre privados. Si quieres indícanos tu nombre para personalizar tu página ;) <%= link_to 'Más información', '/faq', target: 'blank' %></p>

  <%= render 'form' %>
</div>

app/views/users/login.js.erb
$('#<%= @form_context %>').replaceWith('<%= j(render(partial:'sessions/form', locals: {email: @user.email})) %>');

app/views/users/new.html.erb
<% title("Alta usuario")  %>

<div class="cont clearfix">

  <%= render 'alerts' %>

  <%= flush_the_flash %>

  <% if params[:pro] == 'true' %>
    <h2>Descarga nuestra guía: Conectando con tus vecinos</h2>

    <div class="download_guide">

      <i class="fa fa-file-text-o fa-lg"></i>

      <p><strong>Gobierto te ayuda a conectar mejor con tus vecinos</strong>. Gobierto crea herramientas de bajo coste para mejorar tu comunicación y mejorar
        la percepción de tus vecinos sobre tu actividad. Regístrate para descargar la guía, o si ya tienes cuenta <%= link_to 'haz login', login_path %></p>

    </div>

  <% else %>
    <h2>Pide que tu alcalde añada información en Gobierto Presupuestos Municipales</h2>

    <p>Indícanos cuál es tu municipio y nos encargaremos de hacerle llegar tu petición de más información a sus responsables. Te avisaremos si hay respuesta. Si ya tienes cuenta en Gobierto, <%= link_to 'entra aquí', login_path %></p>
  <% end %>

  <div class="form clearfix">

    <%= render 'alerts' %>

    <%= form_for @user do |f| %>
      <%= render partial: 'basic_fields', locals: { f: f} %>

      <div class="form_item full submit_item">
        <div class="form_item_cont clearfix">
          <div class="conditions">
            <p>También recibirás novedades sobre Gobierto Presupuestos Municipales de vez en cuando. Podrás dejar de recibir cuando quieras.</p>
              <label><%= f.check_box :terms_of_service %> He leído el <%= link_to 'Aviso legal', gobierto_budgets_legal_legal_path, target: 'blank' %> y la <%= link_to 'Política de privacidad', gobierto_budgets_legal_privacy_path, target: 'blank' %></label>
          </div>
          <%= hidden_field_tag :back_url, request.referer %>
          <input type="submit" class="submit" value="Enviar">
        </div>
      </div>

    <% end %>
  </div>

  <p>¿Ya tienes una cuenta en Gobierto? <%= link_to "Haz login", login_path %></p>

</div>

app/views/users/verify.html.erb
<div class="cont clearfix">
  
  <%= flush_the_flash %>
  <h1>Venga, ya casi estamos</h1>
  <p class="highlight">Confirma tus datos para poder seguir las actualizaciones de los municipios que elijas, interactuar con tus representantes públicos, y más. Tus datos y opiniones serán siempre privados.</p>

  <%= render 'form' %>
  
</div>